server:
  port: 4000
  servlet:
    context-path: /

---
spring:
  application:
    name: gateway-lee-demo
  nodeId: ${nodeId:1}
  redis:
    host: 10.138.61.139
    port: 6900
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: ["health","prometheus"]
---
spring:
  cloud:
    consul:
      discovery:
        health-check-interval: 5s
        health-check-critical-timeout: 20s
        health-check-timeout: 5s
        enabled: true
        register: true
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      host: localhost
      port: 8500

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: consul-service-demo
        #uri: http://localhost:4000
        uri: http://baidu.com:80/
        predicates:
        - Path=/baidu/*
        filters:
        #- stripPrefix=1
        - CustomFilter
#        - name: RequestRateLimiter
#          args:
#            redis-rate-limiter.replenishRate: 1  # 令牌桶的容积
#            redis-rate-limiter.burstCapacity: 2  # 流速 每秒
#            key-resolver: "#{@remoteAddrKeyResolver}" #SPEL表达式去的对应的bean
